ALTER SESSION SET CONTAINER = FREEPDB1;

--SCHEMA 1: LEDGER_DB
CREATE USER core_banking_user IDENTIFIED BY core_banking123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE,
CREATE SEQUENCE, CREATE VIEW TO core_banking_user;

--SCHEMA 2: Transaction
CREATE USER sell_foreign_user IDENTIFIED BY sell_foreign123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE,
CREATE SEQUENCE, CREATE VIEW TO sell_foreign_user;

COMMIT;
EXIT;
