ALTER SESSION SET CONTAINER = FREEPDB1;

--SCHEMA 1: LEDGER_DB
CREATE USER ledger_user IDENTIFIED BY ledger123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE,
CREATE SEQUENCE, CREATE VIEW TO ledger_user;

--SCHEMA 2: Transaction
CREATE USER transaction_user IDENTIFIED BY transaction123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE,
CREATE SEQUENCE, CREATE VIEW TO transaction_user;

COMMIT;
EXIT;
