ALTER SESSION SET CONTAINER = FREEPDB1;

--CHEMA 1: LEDGER_DB (cho Account Ledger Service)
CREATE USER ledger_user IDENTIFIED BY ledger123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE,
CREATE SEQUENCE, CREATE VIEW TO ledger_user;

--SCHEMA 2: AUDIT_DB (cho Audit Log Service)
CREATE USER audit_user IDENTIFIED BY audit123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE,
CREATE SEQUENCE, CREATE VIEW TO audit_user;

COMMIT;
EXIT;
