

INSERT INTO LEDGER_USER.ACCOUNT  (ACCOUNT_NUMBER, OWNER_NAME, BALANCE, CURRENCY, CREATED_AT, UPDATED_AT)
VALUES ('ACC10001', 'Nguyen Van A', 10000.0000, 'USD', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO LEDGER_USER.ACCOUNT  (ACCOUNT_NUMBER, OWNER_NAME, BALANCE, CURRENCY, CREATED_AT, UPDATED_AT)
VALUES ('ACC20002', 'Tran Thi B', 5000000.0000, 'VND', SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO LEDGER_USER.ACCOUNT  (ACCOUNT_NUMBER, OWNER_NAME, BALANCE, CURRENCY, CREATED_AT, UPDATED_AT)
VALUES ('ACC30003', 'Le Van C', 5000.0000, 'EUR', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
