server:
  port: 8082

spring:
  application:
    name: currency-exchange-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual   # Manual ACK
        prefetch: 1

fxrates:
  api:
    base-url: https://api.fxratesapi.com
    timeout-seconds: 10

logging:
  level:
    com.omnibank.exchange: DEBUG